/*
 * Navratove kody
 * Jan Fruhauf xfruha00
 */

#ifndef IFJPROJECT_CLION_ERROR_H
#define IFJPROJECT_CLION_ERROR_H

#define SCANNER_OK 11
#define SCANNER_ERROR 1
#define SYNTAX_OK 22
#define SYNTAX_ERROR 2
#define SEM_UNDEF_REDEF_ERROR 3
#define SEM_DATA_TYPE_ERROR 4
#define SEM_COMPATIBILITY_ERROR 5
#define SEM_FUNC_ERROR 6
#define SEM_OTHER_ERROR 7
#define SEM_ZERO_DIV_ERROR 9
#define INTERN_ERROR 99

#endif //IFJPROJECT_CLION_ERROR_H
